export const GET_CAUSES = 'GET_CAUSES';
export const GET_CAUSES_SUCCESS = 'GET_CAUSES_SUCCESS';
export const GET_CAUSES_FAIL = 'GET_CAUSES_FAIL';

export const REGISTER_CAUSE = 'REGISTER_CAUSE';
export const REGISTER_CAUSE_SUCCESS = 'REGISTER_CAUSE_SUCCESS';
export const REGISTER_CAUSE_FAIL = 'REGISTER_CAUSE_FAIL';

export const UPDATE_STATUS = 'REGISTER_CAUSE';
export const UPDATE_STATUS_SUCCESS = 'REGISTER_CAUSE_SUCCESS';
export const UPDATE_STATUS_FAIL = 'REGISTER_CAUSE_FAIL';

export const UPDATE_VOLUNTEER = 'UPDATE_VOLUNTEER';
export const UPDATE_VOLUNTEER_SUCCESS = 'UPDATE_VOLUNTEER_SUCCESS';
export const UPDATE_VOLUNTEER_FAIL = 'UPDATE_VOLUNTEER_FAIL';

export const GET_CAUSE_BY_OWNER = 'GET_CAUSE_BY_OWNER';
export const GET_CAUSE_BY_OWNER_SUCCESS = 'GET_CAUSE_BY_OWNER_SUCCESS';
export const GET_CAUSE_BY_OWNER_FAIL = 'GET_CAUSE_BY_OWNER_FAIL';

export const GET_CAUSE_BYID = 'GET_CAUSE_BYID';
export const GET_CAUSE_BYID_SUCCESS = 'GET_CAUSE_BYID_SUCCESS';
export const GET_CAUSE_BYID_FAIL = 'GET_CAUSE_BYID_FAIL';