export const GET_CAUSES = 'GET_CAUSES';
export const GET_CAUSES_SUCCESS = 'GET_CAUSES_SUCCESS';
export const GET_CAUSES_FAIL = 'GET_CAUSES_FAIL';
export const GET_CAUSES_REQUESTED = 'GET_CAUSES_REQUESTED';