// export const GET_USERS = 'GET_USERS';
// export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
// export const GET_USERS_FAIL = 'GET_USERS_FAIL';
// export const GET_USERS_REQUESTED = 'GET_USERS_REQUESTED';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE  = 'USER_LOGIN_FAILURE ';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE  = 'USER_LOGOUT_FAILURE ';

export const GET_USER_BYID = 'GET_USER_BYID';
export const GET_USER_BYID_SUCCESS = 'GET_USER_BYID_SUCCESS';
export const GET_USER_BYID_FAILURE  = 'GET_USER_BYID_FAILURE ';

export const GET_USER_BYUN = 'GET_USER_BYUN';
export const GET_USER_BYUN_SUCCESS = 'GET_USER_BYUN_SUCCESS';
export const GET_USER_BYUN_FAILURE  = 'GET_USER_BYUN_FAILURE ';
